# Generated by Django 3.1.5 on 2021-02-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0001_initial'),
        ('courses', '0004_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='personel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personel.personel'),
        ),
    ]
