# Generated by Django 3.1.5 on 2021-02-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Tag adini giriniz', max_length=50, null=True, verbose_name='Tag'),
        ),
    ]
