# Generated by Django 3.1.5 on 2021-02-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210224_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Firma adini giriniz', max_length=20, unique=True, verbose_name='Firma Adi')),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='courses/x.jpg', upload_to='courses/%y/%m/%d')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
