# Generated by Django 3.1.5 on 2021-03-14 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_firmalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='musteriler',
            field=models.ManyToManyField(blank=True, related_name='courses_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
